### ISSUE TITLE
[Redis Metrics] MonitorKeys 为什么是个Slice呢

### ISSUE THREAD

**Issue by Charlie17Li** [HobbyBear/easymonitor#1]
请问 `monitorKeys` 为啥是个 Slice 呢，使用 map 的话查询复杂度不是 o(1) 吗
https://github.com/HobbyBear/easymonitor/blob/ca89811c7da77c0e1fbae1ac8ed1f564ba6c98a6/infra/redis.go#L11-L13

另外加monitorKeys白名单 是因为如果监控所有 key 担心监控数据量太大吗还是有其他考虑呢

**Comment by HobbyBear** [comment]
可以使用map，考虑对部分key监控的原因主要是防止监控数据量太大，因为我在设计时不是对redis的完整key进行监控，是对redis的业务前缀key进行监控，比如服务名:业务名:uid1 是个完整的key，但是如果记录完整key，将会导致key太多，所以将key记录为 服务名:业务名  进行qps监控，这样服务名:业务名:uid1 和服务名:业务名:uid2的qps都将记为服务名:业务名 ，减少了key的维度，同时能从key的qps反应业务对redis的访问情况。

**Comment by HobbyBear** [comment]
因为实际建造key时，不知道业务key究竟有多长，所以需要业务开发人员进行加白

**Comment by Charlie17Li** [comment]
了解了，感谢
